[package]
name = "aleo-wasm"
version = "0.4.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Toolkit for exporting key Aleo functionality and cryptography to WebAssembly"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/aleo"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies.aleo-rust]
features = [ "wasm" ]
workspace = true

[dependencies.anyhow]
version = "1.0"

[dependencies.getrandom]
version = "0.2"
features = [ "js" ]

[dependencies.hex]
version = "0.4.3"

[dependencies.js-sys]
version = "0.3.52"

[dependencies.rand]
version = "0.8"

[dependencies.reqwest]
version = "0.11.16"

[dependencies.serde_json]
version = "1.0"

[dependencies.snarkvm-synthesizer]
workspace = true
features = [ "wasm", "serial" ]

[dependencies.snarkvm-wasm]
workspace = true
features = [ "console", "fields", "utilities" ]

[dependencies.snarkvm-algorithms]
workspace = true

[dependencies.wasm-bindgen]
version = "0.2"
features = [ "serde-serialize" ]

[dependencies.wasm-bindgen-futures]
version = "0.4.24"

[dependencies.wasm-bindgen-test]
version = "0.3.33"

[dependencies.console_error_panic_hook]
version = "0.1.7"

[dev-dependencies.wasm-bindgen-test]
version = "0.3.33"
